wait(10)
script.Parent.Value.Changed:Once(function(radio)
	warn(radio)
	game.ReplicatedStorage.Radio[radio].Changed:Connect(function(members)
		script.Parent.Frame.TextLabel.Text = tostring(radio).." I "..tostring(members)
		warn(radio)
		warn(members)
	end)
end)

game.ReplicatedStorage.Radio[script.Parent.Value.Value].Changed:Connect(function(members)
	script.Parent.Frame.TextLabel.Text = tostring(script.Parent.Value.Value).." I "..tostring(members)
	warn(script.Parent.Value.Value)
	warn(members)
end)